BookWebRazor/ViewComponents/ShoppingCartViewComponent.cs
using BookWebRazor.BusinessObjects.Constants;
using BookWebRazor.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookWebRazor.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IShoppingCartService _shoppingCartService;
        public ShoppingCartViewComponent(IShoppingCartService shoppingCartService)
        {
            _shoppingCartService = shoppingCartService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId != null)
            {
                if (HttpContext.Session.GetInt32(Consts.SessionCart) is null)
                {
                    int accountId = int.Parse(userId);
                    HttpContext.Session.SetInt32(Consts.SessionCart,
                    _shoppingCartService.Count(cart => cart.AccountId == accountId));
                }
                return View(HttpContext.Session.GetInt32(Consts.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BookWebRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookWebRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookWebRazor.styles.css" asp-append-version="true" />

    @* Boostrap Icon *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    @* Toastr *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

    @* DataTable *@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />

    <style>
        /* On hover and focus, change to solid white and underline */
        .navbar-nav .dropdown-toggle:hover,
        .navbar-nav .dropdown-toggle:focus {
            color: #ffffff !important; /* Solid white */
        }

        .title-two-rows {
            white-space: normal; /* Ensures wrapping */
            display: block; /* Ensure it behaves as a block element */
            overflow: hidden; /* Hide any overflow content */
            text-overflow: ellipsis; /* Add ellipsis for overflow (if needed) */
            line-height: 1.2; /* Adjust line height for spacing */
            height: 2.4em; /* Set height for 2 lines based on line-height */
            max-width: 100%; /* Ensures it takes the full width of container */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-page="/Index">
                    <img src="~/images/book.png" width="30px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-page="/Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(RoleEnum.Admin.ToString()))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white-50" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-page="/CategoryPage/Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-page="/product/index">Product</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link " asp-page="/ShoppingCart/index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-white-50 text-center">
        <div class="container">
            &copy; 2024 - Made by Pham Minh Khoi
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/z5cm19c6b8uqptz3g7dbzagxo2qwa5c1u1ijlbwsafhusc4k/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookWebRazor/Pages/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    // Display an info toast with no title
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}